In [1]:
#!pip3 install keras
#!pip3 install tensorflow-cpu

In [1]:
import numpy as np
import pandas as pd

from keras.models import Sequential
from keras.layers import Dense,Activation,Layer,Lambda

from sklearn.model_selection import train_test_split

In [2]:
dataset=pd.read_csv("penguins.csv")
dataset.head(5)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [3]:
#Removing excess columns
dataset=dataset.drop(["island","sex"],axis=1)
dataset.head(5)

  species  culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0  Adelie              39.1             18.7              181.0       3750.0
1  Adelie              39.5             17.4              186.0       3800.0
2  Adelie              40.3             18.0              195.0       3250.0
3  Adelie               NaN              NaN                NaN          NaN
4  Adelie              36.7             19.3              193.0       3450.0

In [4]:
dataset = dataset.dropna()
dataset.head()

  species  culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
0  Adelie              39.1             18.7              181.0       3750.0
1  Adelie              39.5             17.4              186.0       3800.0
2  Adelie              40.3             18.0              195.0       3250.0
4  Adelie              36.7             19.3              193.0       3450.0
5  Adelie              39.3             20.6              190.0       3650.0

In [5]:
from sklearn.utils import shuffle
dataset = shuffle(dataset)
dataset.head()

,species,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g
23,Adelie,38.2,18.1,185.0,3950.0
137,Adelie,40.2,20.1,200.0,3975.0
300,Gentoo,49.1,14.5,212.0,4625.0
130,Adelie,38.5,17.9,190.0,3325.0
196,Chinstrap,50.9,17.9,196.0,3675.0

In [6]:
pd.isnull(dataset).sum()

species              0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
dtype: int64

In [7]:
X=dataset.drop(["species"],axis=1)
Y=dataset['species'].values
X.head()

     culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
23               38.2             18.1              185.0       3950.0
137              40.2             20.1              200.0       3975.0
300              49.1             14.5              212.0       4625.0
130              38.5             17.9              190.0       3325.0
196              50.9             17.9              196.0       3675.0

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(Y)
print(y)

[0 0 2 0 1 1 2 2 2 2 1 2 0 2 2 0 0 0 1 2 2 0 2 0 0 0 0 0 1 0 0 1 1 0 2 2 0
 2 2 1 2 1 0 2 2 1 2 1 2 0 0 0 0 1 0 0 0 2 1 2 0 0 2 2 2 0 0 1 2 0 0 0 0 1
 2 2 0 0 2 2 0 0 2 1 0 2 2 2 0 0 0 0 1 1 1 2 2 0 0 1 0 0 0 2 0 2 2 0 1 1 2
 0 0 0 0 1 0 0 0 0 0 0 1 2 0 0 0 1 1 2 2 0 0 0 0 0 1 2 1 2 1 0 1 2 2 0 0 1
 2 1 0 0 0 0 0 0 0 2 2 0 2 1 1 2 0 2 2 2 0 0 0 0 2 0 2 0 0 0 2 1 2 2 0 2 2
 2 0 2 0 0 2 0 0 0 2 2 0 0 0 2 0 2 1 0 0 2 0 0 0 2 0 1 0 1 2 2 0 1 2 0 1 2
 0 2 0 1 2 2 0 2 2 0 1 0 1 1 0 0 1 2 0 2 2 2 0 0 0 1 2 0 0 2 0 0 2 1 2 2 1
 0 0 1 0 0 0 1 1 0 1 0 2 2 2 0 1 1 1 2 1 0 2 0 2 1 2 1 1 0 0 0 2 0 0 2 1 0
 2 2 1 2 2 2 0 2 2 0 2 1 1 2 1 2 2 0 1 0 2 1 0 2 0 2 0 0 2 0 2 1 2 2 0 2 0
 0 2 2 2 2 2 0 1 2]

In [16]:
trainX, testX, trainY, testY = train_test_split(X, y, test_size=0.2, random_state=42)
trainX, valX, trainY, valY = train_test_split(trainX, trainY, test_size=0.2, random_state=42)

In [17]:
#SMOTE
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_resample(trainX, trainY)

In [20]:
print("Before OverSampling, counts of label '2': {}".format(sum(trainY==2)))
print("Before OverSampling, counts of label '1': {}".format(sum(trainY==1)))
print("Before OverSampling, counts of label '0': {} \n".format(sum(trainY==0)))

sm = SMOTE(random_state=2)
X_train_res, y_train_res = sm.fit_resample(trainX, trainY)

print("After OverSampling, counts of label '0': {}".format(sum(y_train_res==2)))
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After OverSampling, counts of label '0': {} \n".format(sum(y_train_res==0)))

print('Before OverSampling, the shape of train_X: {}'.format(trainX.shape))
print('Before OverSampling, the shape of train_y: {} \n'.format(trainY.shape))

print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape))

Before OverSampling, counts of label '2': 74
Before OverSampling, counts of label '1': 45
Before OverSampling, counts of label '0': 99

After OverSampling, counts of label '0': 99
After OverSampling, counts of label '1': 99
After OverSampling, counts of label '0': 99

Before OverSampling, the shape of train_X: (218, 4)
Before OverSampling, the shape of train_y: (218,)

After OverSampling, the shape of train_X: (297, 4)
After OverSampling, the shape of train_y: (297,)

model = Sequential()
model.add(Dense(50, activation='relu', input_dim=30))
#model.add(Dense(60, activation='relu'))
#model.add(Dense(70, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [25]:
def getModel(arr):
    model=Sequential()
    for i in range(len(arr)):
        if i!=0 and i!=len(arr)-1:
            if i==1:
                model.add(Dense(arr[i],input_dim=arr[0],kernel_initializer='normal', activation='relu'))
            else:
                model.add(Dense(arr[i],activation='relu'))
    model.add(Dense(arr[-1],kernel_initializer='normal',activation="softmax"))
    model.compile(loss="binary_crossentropy",optimizer='rmsprop',metrics=['accuracy'])
    return model
model=getModel([4,10,1])

In [26]:
model.fit(np.array(trainX),np.array(trainY),epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 2ms/step - loss: 0.2803 - accuracy: 0.2064
Epoch 2/100
7/7 [==============================] - 0s 3ms/step - loss: -0.0320 - accuracy: 0.2064
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 0.0477 - accuracy: 0.2064
Epoch 4/100
7/7 [==============================] - 0s 3ms/step - loss: -0.0541 - accuracy: 0.2064
Epoch 5/100
7/7 [==============================] - 0s 3ms/step - loss: -0.0440 - accuracy: 0.2064
Epoch 6/100
7/7 [==============================] - 0s 3ms/step - loss: -0.1038 - accuracy: 0.2064
Epoch 7/100
7/7 [==============================] - 0s 3ms/step - loss: -0.0506 - accuracy: 0.2064
Epoch 8/100
7/7 [==============================] - 0s 3ms/step - loss: -0.1061 - accuracy: 0.2064
Epoch 9/100
7/7 [==============================] - 0s 3ms/step - loss: -0.1125 - accuracy: 0.2064
Epoch 10/100
7/7 [==============================] - 0s 3ms/step - loss: -0.1482 - accuracy: 0.2064
Epoch 11/100
7/7 [==============================] - 0s 3ms/step - loss: -0.0486 - accuracy: 0.2064
Epoch 12/100
7/7 [==============================] - 0s 3ms/step - loss: -0.2094 - accuracy: 0.2064
Epoch 13/100
7/7 [==============================] - 0s 3ms/step - loss: -0.1873 - accuracy: 0.2064
Epoch 14/100
7/7 [==============================] - 0s 4ms/step - loss: -0.2319 - accuracy: 0.2064
Epoch 15/100
7/7 [==============================] - 0s 3ms/step - loss: -0.2376 - accuracy: 0.2064
Epoch 16/100
7/7 [==============================] - 0s 3ms/step - loss: -0.2911 - accuracy: 0.2064
Epoch 17/100
7/7 [==============================] - 0s 3ms/step - loss: -0.2495 - accuracy: 0.2064
Epoch 18/100
7/7 [==============================] - 0s 3ms/step - loss: -0.1219 - accuracy: 0.2064
Epoch 19/100
7/7 [==============================] - 0s 4ms/step - loss: -0.3315 - accuracy: 0.2064
Epoch 20/100
7/7 [==============================] - 0s 3ms/step - loss: -0.3177 - accuracy: 0.2064
Epoch 21/100
7/7 [==============================] - 0s 3ms/step - loss: -0.3817 - accuracy: 0.2064
Epoch 22/100
7/7 [==============================] - 0s 3ms/step - loss: -0.3989 - accuracy: 0.2064
Epoch 23/100
7/7 [==============================] - 0s 3ms/step - loss: -0.2756 - accuracy: 0.2064
Epoch 24/100
7/7 [==============================] - 0s 3ms/step - loss: -0.2835 - accuracy: 0.2064
Epoch 25/100
7/7 [==============================] - 0s 3ms/step - loss: -0.4439 - accuracy: 0.2064
Epoch 26/100
7/7 [==============================] - 0s 3ms/step - loss: -0.4104 - accuracy: 0.2064
Epoch 27/100
7/7 [==============================] - 0s 3ms/step - loss: -0.4899 - accuracy: 0.2064
Epoch 28/100
7/7 [==============================] - 0s 3ms/step - loss: -0.4459 - accuracy: 0.2064
Epoch 29/100
7/7 [==============================] - 0s 3ms/step - loss: -0.4891 - accuracy: 0.2064
Epoch 30/100
7/7 [==============================] - 0s 3ms/step - loss: -0.4801 - accuracy: 0.2064
Epoch 31/100
7/7 [==============================] - 0s 3ms/step - loss: -0.5654 - accuracy: 0.2064
Epoch 32/100
7/7 [==============================] - 0s 3ms/step - loss: -0.5999 - accuracy: 0.2064
Epoch 33/100
7/7 [==============================] - 0s 3ms/step - loss: -0.5185 - accuracy: 0.2064
Epoch 34/100
7/7 [==============================] - 0s 3ms/step - loss: -0.5972 - accuracy: 0.2064
Epoch 35/100
7/7 [==============================] - 0s 3ms/step - loss: -0.5500 - accuracy: 0.2064
Epoch 36/100
7/7 [==============================] - 0s 3ms/step - loss: -0.6970 - accuracy: 0.2064
Epoch 37/100
7/7 [==============================] - 0s 3ms/step - loss: -0.6071 - accuracy: 0.2064
Epoch 38/100
7/7 [==============================] - 0s 3ms/step - loss: -0.7106 - accuracy: 0.2064
Epoch 39/100
7/7 [==============================] - 0s 3ms/step - loss: -0.7019 - accuracy: 0.2064
Epoch 40/100
7/7 [==============================] - 0s 3ms/step - loss: -0.7278 - accuracy: 0.2064
Epoch 41/100
7/7 [==============================] - 0s 3ms/step - loss: -0.7628 - accuracy: 0.2064
Epoch 42/100
7/7 [==============================] - 0s 3ms/step - loss: -0.8698 - accuracy: 0.2064
Epoch 43/100
7/7 [==============================] - 0s 2ms/step - loss: -0.8179 - accuracy: 0.2064
Epoch 44/100
7/7 [==============================] - 0s 3ms/step - loss: -0.9223 - accuracy: 0.2064
Epoch 45/100
7/7 [==============================] - 0s 3ms/step - loss: -0.9430 - accuracy: 0.2064
Epoch 46/100
7/7 [==============================] - 0s 3ms/step - loss: -0.9760 - accuracy: 0.2064
Epoch 47/100
7/7 [==============================] - 0s 3ms/step - loss: -1.0837 - accuracy: 0.2064
Epoch 48/100
7/7 [==============================] - 0s 2ms/step - loss: -1.0177 - accuracy: 0.2064
Epoch 49/100
7/7 [==============================] - 0s 3ms/step - loss: -1.1083 - accuracy: 0.2064
Epoch 50/100
7/7 [==============================] - 0s 3ms/step - loss: -1.2415 - accuracy: 0.2064
Epoch 51/100
7/7 [==============================] - 0s 3ms/step - loss: -1.0320 - accuracy: 0.2064
Epoch 52/100
7/7 [==============================] - 0s 3ms/step - loss: -1.1160 - accuracy: 0.2064
Epoch 53/100
7/7 [==============================] - 0s 3ms/step - loss: -1.1034 - accuracy: 0.2064
Epoch 54/100
7/7 [==============================] - 0s 3ms/step - loss: -1.3403 - accuracy: 0.2064
Epoch 55/100
7/7 [==============================] - 0s 4ms/step - loss: -1.3547 - accuracy: 0.2064
Epoch 56/100
7/7 [==============================] - 0s 2ms/step - loss: -1.4657 - accuracy: 0.2064
Epoch 57/100
7/7 [==============================] - 0s 3ms/step - loss: -1.4701 - accuracy: 0.2064
Epoch 58/100
7/7 [==============================] - 0s 3ms/step - loss: -1.5519 - accuracy: 0.2064
Epoch 59/100
7/7 [==============================] - 0s 3ms/step - loss: -1.5208 - accuracy: 0.2064
Epoch 60/100
7/7 [==============================] - 0s 3ms/step - loss: -1.6150 - accuracy: 0.2064
Epoch 61/100
7/7 [==============================] - 0s 3ms/step - loss: -1.7351 - accuracy: 0.2064
Epoch 62/100
7/7 [==============================] - 0s 3ms/step - loss: -1.8216 - accuracy: 0.2064
Epoch 63/100
7/7 [==============================] - 0s 3ms/step - loss: -1.8703 - accuracy: 0.2064
Epoch 64/100
7/7 [==============================] - 0s 3ms/step - loss: -1.8270 - accuracy: 0.2064
Epoch 65/100
7/7 [==============================] - 0s 3ms/step - loss: -1.8963 - accuracy: 0.2064
Epoch 66/100
7/7 [==============================] - 0s 3ms/step - loss: -2.0898 - accuracy: 0.2064
Epoch 67/100
7/7 [==============================] - 0s 3ms/step - loss: -2.0835 - accuracy: 0.2064
Epoch 68/100
7/7 [==============================] - 0s 3ms/step - loss: -2.3131 - accuracy: 0.2064
Epoch 69/100
7/7 [==============================] - 0s 4ms/step - loss: -2.1923 - accuracy: 0.2064
Epoch 70/100
7/7 [==============================] - 0s 3ms/step - loss: -2.3079 - accuracy: 0.2064
Epoch 71/100
7/7 [==============================] - 0s 3ms/step - loss: -2.5269 - accuracy: 0.2064
Epoch 72/100
7/7 [==============================] - 0s 3ms/step - loss: -2.5998 - accuracy: 0.2064
Epoch 73/100
7/7 [==============================] - 0s 3ms/step - loss: -2.7211 - accuracy: 0.2064
Epoch 74/100
7/7 [==============================] - 0s 3ms/step - loss: -2.5983 - accuracy: 0.2064
Epoch 75/100
7/7 [==============================] - 0s 3ms/step - loss: -2.8017 - accuracy: 0.2064
Epoch 76/100
7/7 [==============================] - 0s 3ms/step - loss: -2.9890 - accuracy: 0.2064
Epoch 77/100
7/7 [==============================] - 0s 3ms/step - loss: -2.9872 - accuracy: 0.2064
Epoch 78/100
7/7 [==============================] - 0s 4ms/step - loss: -3.0637 - accuracy: 0.2064
Epoch 79/100
7/7 [==============================] - 0s 3ms/step - loss: -3.3297 - accuracy: 0.2064
Epoch 80/100
7/7 [==============================] - 0s 3ms/step - loss: -3.4836 - accuracy: 0.2064
Epoch 81/100
7/7 [==============================] - 0s 3ms/step - loss: -3.4649 - accuracy: 0.2064
Epoch 82/100
7/7 [==============================] - 0s 3ms/step - loss: -3.2125 - accuracy: 0.2064
Epoch 83/100

7/7 [==============================] - 0s 3ms/step - loss: -3.7229 - accuracy: 0.2064
Epoch 84/100
7/7 [==============================] - 0s 3ms/step - loss: -3.7767 - accuracy: 0.2064
Epoch 85/100
7/7 [==============================] - 0s 2ms/step - loss: -3.6146 - accuracy: 0.2064
Epoch 86/100
7/7 [==============================] - 0s 3ms/step - loss: -3.8697 - accuracy: 0.2064
Epoch 87/100
7/7 [==============================] - 0s 3ms/step - loss: -4.0859 - accuracy: 0.2064
Epoch 88/100
7/7 [==============================] - 0s 3ms/step - loss: -3.8869 - accuracy: 0.2064
Epoch 89/100
7/7 [==============================] - 0s 3ms/step - loss: -4.3813 - accuracy: 0.2064
Epoch 90/100
7/7 [==============================] - 0s 3ms/step - loss: -4.2549 - accuracy: 0.2064
Epoch 91/100
7/7 [==============================] - 0s 3ms/step - loss: -4.5749 - accuracy: 0.2064
Epoch 92/100
7/7 [==============================] - 0s 3ms/step - loss: -4.7162 - accuracy: 0.2064
Epoch 93/100
7/7 [==============================] - 0s 3ms/step - loss: -4.7662 - accuracy: 0.2064
Epoch 94/100
7/7 [==============================] - 0s 3ms/step - loss: -4.6853 - accuracy: 0.2064
Epoch 95/100
7/7 [==============================] - 0s 3ms/step - loss: -4.9699 - accuracy: 0.2064
Epoch 96/100
7/7 [==============================] - 0s 2ms/step - loss: -4.7917 - accuracy: 0.2064
Epoch 97/100
7/7 [==============================] - 0s 2ms/step - loss: -5.2552 - accuracy: 0.2064
Epoch 98/100
7/7 [==============================] - 0s 3ms/step - loss: -5.3698 - accuracy: 0.2064
Epoch 99/100
7/7 [==============================] - 0s 2ms/step - loss: -5.5907 - accuracy: 0.2064
Epoch 100/100
7/7 [==============================] - 0s 2ms/step - loss: -5.2346 - accuracy: 0.2064

In [27]:
scores=model.evaluate(np.array(valX),np.array(valY))
print("Loss:",scores[0])
print("Accuracy",scores[1]*100)

2/2 [==============================] - 0s 3ms/step - loss: -19.6486 - accuracy: 0.1455
Loss: -19.648588180541992
Accuracy 14.5454540848732

In [36]:
predY=model.predict(np.array(testX))
predY=np.round(predY).astype(int).reshape(1,-1)[0]

#Plot predictions
from sklearn.metrics import confusion_matrix
m=confusion_matrix(predY,testY)
ct = pd.crosstab(predY,testY)
print('Confusion Matrix')
print(ct)

Confusion Matrix
col_0   0   1   2
row_0
1      29  15  25

In [43]:
tn, fn, fp, tp, *o =confusion_matrix(predY,testY).ravel()

In [44]:
tn, fn, fp, tp, *o=confusion_matrix(predY,testY).ravel()
m=pd.crosstab(predY,testY)
print("Confusion matrix")
print(m)
sens=tp/(tp+fn)
spec=tn/(tn+fp)
print("Senstivity:",sens)
print("Specificity:",spec)

Confusion matrix
col_0   0   1   2
row_0
1      29  15  25
Senstivity: 1.0
Specificity: nan

/tmp/ipykernel_19745/1907610561.py:6: RuntimeWarning: invalid value encountered in long_scalars
  spec=tn/(tn+fp)